---
application_name: Omnirisk Solutions
business_name: Omnirisk Solutions Pty Ltd
business_address: |-
  30 Pointer Crescent,
  Garsfontein,
  Pretoria,
  Gauteng, 0042
domain: https://entresure.weareclued.com
support_email: tech@entreusure.weareclued.com
default_from_email: Omnirisk Support <no-reply@entresure.weareclued.com>
background_job_processor: async
email_provider: mandrill
personal_accounts: false
apns: false
fcm: false
integrations:
- honeybadger
- rollbar
omniauth_providers:
payment_processors:
multitenancy:
- path
gems:
- acts_as_tenant
- rack-attack
- whenever
